# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common-4.19/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter MiThoriumSSI Mi8937 Mi8953 Mi8953_4_19 Mi439_4_19 Tiare oxygen ysl uter vince onc,$(TARGET_DEVICE)),)

endif
